#Facebook login
[login]
username = ""
password = ""

# Link fb threads to gateways
# You get the thread id when a message is recived by the default gateway. 123 is used as thread id below.
[threads]
   [threads.123]
   gateway = "gateway2" 

   [threads.1234]
   gateway = "gateway3" 

# Link user id to usernames
[users]
   [users.123]
   username = "Joe Someone" 
